baseURL = "https://feserr-portfolio.netlify.com"
languageCode = "en-gb"
title = "Elías Serrano"
theme = "hugo-resume"

[params]
    firstName = "Elías"
    lastName = "Serrano"
    address = "Valencia, Spain"
    # phone = "1-555-555-1234"
    contactNote = "Software Developer"
    profileImage = "images/user.png"
    email = "fraserm1989@gmail.com"
    description = "Experienced software developer who loves new challenges in the day-to-day."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/franciscoeliasserrano/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/feserr_/"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/3081041/feserr"
    icon = "stack-overflow"

[params.google.analytics]
    trackerID = "UA-144975084-1"
